MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  BACKBONE:
    NAME: "build_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
    # NORM: "SyncBN"
  ANCHOR_GENERATOR:
    # SIZES: [[12], [24], [48], [96], [192]]  # One size for each in feature map
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("waymo_train",)
  TEST: ("waymo_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.02
  # STEPS: (6000, 9000)
  # MAX_ITER: 12000
  STEPS: (12000, 18000)
  MAX_ITER: 24000
  # STEPS: (30000, 40000)
  # MAX_ITER: 45000
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  # MIN_SIZE_TRAIN: (640,  800, 960, 1120, 1280)
  MIN_SIZE_TEST: 1280
  MAX_SIZE_TRAIN: 2000
  MAX_SIZE_TEST: 2000
  FORMAT: "BGR"
VERSION: 2
